sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t thabisomagwaza/frontend-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thabisomagwaza/frontend-react npm run test
